
#Projects ??


applications:

  - name: guestbook
    project: default
    source:
      # repoURL: https://github.com/Energinet-DataHub/eo-base-environment
      # targetRevision: main
      # path: .
      plugin:
        name: helm-overdrive
        env:
          - name: helm-repo
            value: https://cloudnativeapp.github.io/charts/curated/
          - name: helm-chart
            value: guestbook
          - name: chart-version
            value: 0.2.0

          - name: base-config
            value: base/applications/guestbook/guestbook_values.yaml
          - name: base-extra
            value: base/applications/guestbook/extra
          - name: base-globals-yaml
            value: base/global.yaml

          - name: env-config
            value: env/{{ .Values.env }}/applications/guestbook/guestbook_values.yaml
          - name: env-extra
            value: env/{{ .Values.env }}/applications/guestbook/extra
          - name: env-globals-yaml
            value: env/{{ .Values.env }}/global.yaml

# global.yaml = base-globals.yaml yaml-merge env-globals.yaml
# base.yaml = gotemplate base-config global.yaml
# env.yaml = gotemplate env-config global.yaml
# conf.yaml = base.yaml yaml-merge env.yaml
# helm template chart conf.yaml > manifest.yaml
# helm create extra
# rm -r ./extra/templates/*
# cp -r ./base-extra ./extra/template/
# cp -r ./env-extra ./extra/template/
# cp conf.yaml ./extra/values.yaml
# helm template ./extra >> manifest.yaml
# return manifest.yaml




  - name: ingress
    source:
      repoURL: "https://github.com/distributed-technologies/services-traefik.git"
      chart: traefik
      targetRevision: 10.14.2

  
      

  - name: ingress
    source:
      repoURL: https://distributed-technologies.github.io/helm-charts/
      chart: grafana
      targetRevision: 0.1.10
      valuesFile: "grafana/grafana_values.yaml"
    plugin:
      name: argocd-overdrive
      # environment variables passed to the plugin
      env:
        #- name: repo
        #  value: https://github.com/Energinet-DataHub/eo-base-environment # Posibly automatic
        - name: folder
          value: applications/grafana
        - name: overrides
          value: applications/grafana/extra

  - name: traefik
    # ...

  - name: cert-manager
    # ...

  - name: loki
    # ...

  - name: prometheus
    # ...

  - name: sealed-secrets
    # ...

# helm template
# concat overrides
# -> stdout